project:
  type: website
  output-dir: docs

website:
  title: "Data Science: Andy Xiao"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "DS002 Projects"
        menu:
        - href: Dataset1.qmd
          text: Income Inequality
        - href: Dataset2.qmd
          text: Pixar Films


      


format:
  html:
    theme:
      dark: Cyborg
    css: styles.css
    toc: true
    page-layout: full



